In [1]:
import numpy as np

In [ ]:
# 1. Create 1-D and 2-D arrays using Numpy. Also convert 1-D array to appropriate 2-D using reshape() and add two arrays. Also find the shape of a 2-D array using shape().
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d)
arr_2d = np.array([[7,8,9],[10,11,12]])
print(arr_2d)

[1 2 3 4 5 6]
[[ 7  8  9]
 [10 11 12]]


In [3]:
# Convert 1-D array to appropriate 2-D using reshape() and add two arrays.
new_2d = arr_1d.reshape(2,3)
print(new_2d)

added_arr = new_2d + arr_2d
print(added_arr)

print(added_arr.shape)

[[1 2 3]
 [4 5 6]]
[[ 8 10 12]
 [14 16 18]]
(2, 3)


In [7]:
b = arr_2d.shape
print(b)

(2, 3)


In [ ]:
# 2. Use an appropriate indexing method to access the last data of the 2-D array.