In [12]:
import numpy as np


In [13]:
# Generate dummy dataset
X = np.random.randint(10,50,100).reshape(20,5)
print(X.shape)

# Mean center the data
X_meaned = X - np.mean(X , axis = 0)
print(X_meaned)

(20, 5)
[[ 16.1   14.05   2.6  -13.8    1.65]
 [  2.1    9.05  -5.4  -15.8    9.65]
 [  8.1   12.05   7.6    9.2    8.65]
 [ 18.1  -10.95  -9.4   12.2   -7.35]
 [ -3.9   -9.95  -5.4    7.2   -1.35]
 [-14.9   -3.95  -1.4   12.2   -2.35]
 [-15.9    2.05  21.6    9.2    9.65]
 [ 17.1   -8.95  19.6   11.2    7.65]
 [ -4.9   -0.95 -11.4   -5.8    8.65]
 [-10.9   -5.95  -4.4   -9.8   -2.35]
 [-15.9   -6.95 -11.4   -0.8  -13.35]
 [ 11.1   -5.95   2.6   12.2  -11.35]
 [  5.1   15.05 -12.4   -0.8  -13.35]
 [ 11.1   13.05  13.6   -4.8  -17.35]
 [ 19.1  -12.95  -9.4  -12.8   16.65]
 [-12.9    7.05   9.6    5.2   15.65]
 [ -7.9   -2.95  24.6   -2.8  -17.35]
 [-14.9   -7.95 -10.4   -7.8   -8.35]
 [-15.9   -0.95 -12.4   -9.8    7.65]
 [ 10.1    6.05  -8.4    6.2    8.65]]


In [14]:
cov_mat = np.cov(X_meaned , rowvar = False)
print(cov_mat)

[[172.51578947  14.31052632   6.67368421   7.71578947   8.08947368]
 [ 14.31052632  83.52368421  19.07368421 -16.8          3.43947368]
 [  6.67368421  19.07368421 147.72631579  37.55789474  -4.93684211]
 [  7.71578947 -16.8         37.55789474  93.74736842  -7.87368421]
 [  8.08947368   3.43947368  -4.93684211  -7.87368421 119.81842105]]


In [15]:
# Calculate Eigenvalues and Eigenvectors
eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)

In [16]:
# Sort the eigenvalues in descending order
sorted_index = np.argsort(eigen_values)[::-1]

sorted_eigenvalue = eigen_values[sorted_index]

# Similarly sort the eigenvectors
sorted_eigenvectors = eigen_vectors[:,sorted_index]

In [17]:
# Select the first n eigenvectors (n is desired dimension)
n_components = 2
eigenvector_subset = sorted_eigenvectors[:,0:n_components]

In [18]:
# Transform the data
x_reduced = np.dot(eigenvector_subset.transpose() , X_meaned.transpose() ).transpose()

# Visulaize the shape
print(x_reduced.shape)

(20, 2)
